# Generated by Django 4.2.5 on 2024-02-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deployed_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
