# Generated by Django 4.2.5 on 2023-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=150),
        ),
    ]
