# Generated by Django 4.2.5 on 2023-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
