# Generated by Django 4.2.5 on 2023-09-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(max_length=150),
        ),
    ]
