# Generated by Django 4.2.5 on 2023-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
