# Generated by Django 4.2.5 on 2023-12-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_jobseeker_profile_pic_alter_jobseeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
