# Generated by Django 4.2.5 on 2023-12-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='organization/profile_pics/'),
        ),
    ]
