# Generated by Django 4.2.5 on 2023-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
    ]
