# Generated by Django 4.2.5 on 2023-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
