# Generated by Django 4.2.5 on 2023-09-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_application_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='deadline',
        ),
    ]
