# Generated by Django 4.2.5 on 2023-09-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_jobprofile'),
        ('jobprofile', '0001_initial'),
        ('applicant', '0004_alter_application_job_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobprofile.jobprofile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobseeker'),
        ),
    ]
